print("Hey, it's Milo, the chatbot!")
answer = input("How are you today? ")
print(answer)
answer = input("What's your name? ")
print(answer)
print("It's nice to meet you!")
print("How can I help you today?")
print("I want to learn more about the admission process.")
print("Welcome to this website, I will be your guide!")
print("What is your SAT score? ")
answer = input()
print("Let me explain what the SAT is: It is a standardized test that many colleges require students to take and submit their score. Another option is the ACT which is a different type of standardized test.")
answer = input()
print(answer)
answer = input("What extracurriculars do you have? ")
print(answer)
answer = input("What topics are you writing about for the supplemental essays? ")
print(answer)
rating = input("Please rate my performance: Good, \nMediocre, \nPoor")
if rating.lower() == "Good":
    print("I'm glad you liked my responses!")
elif rating.lower() == "Mediocre":
    print("Thanks for the feedback-- I'll try to improve in the future!")
else:
    print("I'm so sorry about that, I'll make sure to work on it!")